ZeusWPI/hydra-android

app/src/main/java/be/ugent/zeus/hydra/fragments/resto/RestoFragment.java

The old fragment was not always deleted, and showed an older menu instead.

Fix for resto tab showing wrong menu

---

app/src/main/java/be/ugent/zeus/hydra/activities/SchamperArticleActivity.java
app/src/main/java/be/ugent/zeus/hydra/fragments/InfoFragment.java
app/src/main/java/be/ugent/zeus/hydra/models/info/InfoItem.java
app/src/main/java/be/ugent/zeus/hydra/models/info/InfoType.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/InfoViewHolder.java
app/src/main/res/drawable/ic_open_in_browser_24dp.xml
app/src/main/res/layout/activity_info_sub_item.xml
app/src/main/res/menu/menu_event.xml
app/src/main/res/menu/menu_schamper.xml

Fixes #67.
Every type of info card now shows the correct icon. Cards that open in an internal webview intentionally have no icon, since they open in the same app. The icons are official Material Design icons.
Screenshot:

Icons for info types.

---

app/src/main/AndroidManifest.xml
app/src/main/java/be/ugent/zeus/hydra/activities/minerva/AuthActivity.java
app/src/main/java/be/ugent/zeus/hydra/fragments/home/HomeFragment.java
app/src/main/java/be/ugent/zeus/hydra/fragments/minerva/MinervaFragment.java
app/src/main/java/be/ugent/zeus/hydra/fragments/preferences/MinervaFragment.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/AccountUtils.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/MinervaAuthenticator.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/MinervaConfig.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/MinervaService.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/OAuthConfiguration.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/models/BearerToken.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/models/GrantInformation.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/models/UserAttributes.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/requests/AccessTokenRequest.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/requests/NewAccessTokenRequest.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/requests/RefreshAccessTokenRequest.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/requests/TokenRequestInterceptor.java
app/src/main/java/be/ugent/zeus/hydra/minerva/sync/SyncUtils.java
app/src/main/java/be/ugent/zeus/hydra/requests/common/TokenRequest.java
app/src/main/java/be/ugent/zeus/hydra/requests/minerva/MinervaRequest.java
app/src/main/java/be/ugent/zeus/hydra/requests/minerva/UserInfoRequest.java

Update endpoints to the production ones.
I've taken the opportunity to move the `auth` package under the `minerva` package, now everything related to minerva (except fragments & activities) is under one package (sync, database, auth).

Upgrade Minerva to production

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/activities/ActivityDetailActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/preferences/AssociationSelectPrefActivity.java
app/src/main/java/be/ugent/zeus/hydra/fragments/ActivitiesFragment.java
app/src/main/java/be/ugent/zeus/hydra/fragments/home/EventCallback.java
app/src/main/java/be/ugent/zeus/hydra/models/association/Activities.java
app/src/main/java/be/ugent/zeus/hydra/models/association/Association.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/adapters/ActivityListAdapter.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/adapters/MultiSelectListAdapter.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/ActivityViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/requests/common/ProcessableCacheRequest.java
app/src/main/java/be/ugent/zeus/hydra/requests/events/ActivitiesRequest.java
app/src/main/java/be/ugent/zeus/hydra/requests/events/FilteredEventRequest.java

The search in the association selection activity messed up saving the correct associations. This should fix that. Views are also updated after changes are made now.
This also improves the search a bit (e.g. searching `vtk` now works) and adds clickable links in the event descriptions (e.g. the Zeus S10 visit text).
Fixes #108

Improvements & fixes for associations

---

app/src/main/java/be/ugent/zeus/hydra/activities/minerva/AgendaActivity.java
app/src/main/java/be/ugent/zeus/hydra/fragments/home/HomeFeedFragment.java
app/src/main/java/be/ugent/zeus/hydra/fragments/home/requests/EventRequest.java
app/src/main/java/be/ugent/zeus/hydra/fragments/home/requests/MinervaAgendaRequest.java
app/src/main/java/be/ugent/zeus/hydra/fragments/home/requests/MinervaAnnouncementRequest.java
app/src/main/java/be/ugent/zeus/hydra/minerva/agenda/AgendaDao.java
app/src/main/java/be/ugent/zeus/hydra/minerva/agenda/AgendaExtractor.java
app/src/main/java/be/ugent/zeus/hydra/models/cards/EventCard.java
app/src/main/java/be/ugent/zeus/hydra/models/cards/HomeCard.java
app/src/main/java/be/ugent/zeus/hydra/models/cards/MinervaAgendaCard.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/adapters/HomeCardAdapter.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/home/EventCardViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/home/MinervaAgendaViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/minerva/AgendaViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/sko/LineupViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/utils/DateUtils.java
app/src/main/res/layout/home_minerva_agenda_card.xml
app/src/main/res/layout/home_minerva_announcement_card.xml
app/src/main/res/layout/item_minerva_home_agenda.xml
app/src/main/res/values/array.xml

Add the Minerva agenda items to the home feed.
When the Minerva API returns Centauro things as well, we should evaluate if putting every agenda item for the next month in the home feed doesn't clutter it too much.
Note: git merging caused the two commits with the same name.

Add Minerva agenda to homefeed

---

app/src/main/java/be/ugent/zeus/hydra/activities/EventDetailActivity.java

On the detail page of the events, the timezone was not applied to the start/end date, causing them to appear in UTC instead of the local time.

Fix wrong time on events

---

build.gradle

This version of the Android Gradle plugin uses Gradle 3.3 which brings some speed improvements and new features, but more importantly, enables Instant Run in Android Studio.
See: https://developer.android.com/studio/run/index.html#instant-run

Bump Android Gradle plugin to version 2.3.1

---

app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/AgendaDao.java
app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/AnnouncementDao.java
app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/CourseDao.java
app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/CourseExtractor.java
app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/CourseTable.java
app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/DatabaseBroadcaster.java
app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/DatabaseHelper.java
app/src/main/java/be/ugent/zeus/hydra/data/models/minerva/Course.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/BaseActivity.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/adapters/DiffSearchableItemAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/adapters/EmptyItemAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/ordering/DragCallback.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/ordering/ItemDragHelperAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/ordering/OnStartDragListener.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/LibraryListAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/LibraryListFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/MinervaCourseAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/MinervaCourseViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/MinervaFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/minerva/overview/AgendaAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/minerva/overview/AnnouncementAdapter.java
app/src/main/res/drawable/ic_drag_handle.xml
app/src/main/res/layout/item_minerva_course.xml

Add functionality to re-order Minerva courses, as requested in #136.
Of course this is only locally; on other devices or after data wipe the ordering is lost. The long term plan should still be to convince the Minerva people to adjust the API, but alas, what can you do?
Screenshot:

Minerva ordering

---

app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/content/schamper/SchamperCard.java

We used to display two months of articles, but now we only display one month.

Fix Schamper article priority calculation

---

app/src/main/java/be/ugent/zeus/hydra/data/network/JsonSpringRequest.java

http://student.ugent.be/hydra/api/3.0/recent_news.json currently returns nothing (0 bytes), and this crashed the app. Prevent crashing and log this to Firebase, since this is a server-side error that should be fixed.

Handle and log cases where the server returns nothing

---

app/src/main/java/be/ugent/zeus/hydra/repository/requests/Result.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/FeedLiveData.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/operations/FeedOperation.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/operations/RemoveOperation.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/operations/RequestOperation.java

Errors were not properly propagated to the home feed, which means cached data was not used when available if there was no network.

Fix home feed not using cache

---

app/src/main/AndroidManifest.xml
app/src/main/java/be/ugent/zeus/hydra/ui/onboarding/HomeFeedFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/preferences/HomeFeedPrefActivity.java
app/src/main/java/be/ugent/zeus/hydra/ui/preferences/HomeFeedSelectFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/preferences/HomeFragment.java
app/src/main/res/layout-land/fragment_onboarding_home.xml
app/src/main/res/layout/activity_preferences_homefeed.xml
app/src/main/res/layout/fragment_home_feed_select.xml
app/src/main/res/layout/fragment_onboarding_home.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_home_feed.xml

The settings now work in the same way as the onboarding for selecting which cards to show.

Implement #126

---

app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventFragment.java
app/src/main/res/menu/menu_main_events.xml

Add searching to DSA activities.
An event appears as a match if the event's title or the association's name contains the search string. We don't search through the description at the moment. Searching happens on the main thread (as it is more a filter than a real search), so including descriptions could cause problems (because they can become too long).
Implements #117 (finally).

Add searching to activities

---

app/src/main/java/be/ugent/zeus/hydra/HydraApplication.java

This will log violations of strict mode. In the future we might change the penalty for violating this to crashing instead of logging.

Enable strict mode in debug builds

---

app/src/main/java/be/ugent/zeus/hydra/data/models/schamper/Article.java
app/src/main/java/be/ugent/zeus/hydra/data/sync/minerva/helpers/NotificationHelper.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/content/schamper/SchamperViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/schamper/SchamperViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/utils/ColourUtils.java
app/src/main/res/layout/item_schamper.xml

Since this was not completed entirely during the codenight, I have implemented it here, using the values from the API.
In the main Schamper list I have used the accent colour as the background colour, since I think it looks nice, but if people don't like it, we can easily change it back.
In the homefeed:
In the main list:

Add Schamper colours

---

app/src/main/java/be/ugent/zeus/hydra/data/network/requests/minerva/AgendaDuplicateDetector.java
app/src/main/java/be/ugent/zeus/hydra/data/sync/minerva/helpers/CalendarSync.java
app/src/main/java/be/ugent/zeus/hydra/ui/preferences/MinervaFragment.java
app/src/main/java/be/ugent/zeus/hydra/utils/StringUtils.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_minerva.xml

- Add an option to add the course's name as a prefix to events in the device calendar.
* The prefix can be the full app name, or a generated acronym.
* This will not happen if the title of the event is already the course name. For example, with both options enabled, for the course `Machinaal leren`, two events A: `Machinaal leren` and B: `Statistische grondslagen`, the result would be A: `Machinaal leren` (no change) and B: `ML: Statistische grondslagen`.
- Improve duplication detection
* If the API indicates an event was hidden, we now also hide the event.
* In rare cases where there are multiple events on the same time for the same course with different pairs of titles, they are also recognised. For example, assume we have for some course event A, B, C and D at the same time. Further, …

Add prefix options and improve duplicate detection

---

app/src/main/java/be/ugent/zeus/hydra/common/database/migrations/Migration_6_7.java

The calendar table has since been renamed, resulting in a crash when executing this migration.

Do not use constants in the migrations

---

app/build.gradle
app/config.properties
app/src/main/java/be/ugent/zeus/hydra/common/reporting/BaseEvents.java
app/src/main/java/be/ugent/zeus/hydra/common/reporting/FirebaseEvents.java
app/src/main/java/be/ugent/zeus/hydra/common/reporting/Reporting.java
app/src/main/java/be/ugent/zeus/hydra/feed/commands/DisableAssociationCommand.java
app/src/main/java/be/ugent/zeus/hydra/feed/commands/DisableIndividualCard.java
app/src/main/java/be/ugent/zeus/hydra/feed/commands/DisableTypeCommand.java
app/src/main/java/be/ugent/zeus/hydra/feed/commands/DismissalEvent.java
app/src/test/java/be/ugent/zeus/hydra/feed/commands/DisableIndividualCardTest.java

As said in the commit; this is useful for two reasons:
- This might provide insightful data, so we can prioritise the cards better.
- There are some very rare crashes related to card dismissals. This will allow us to collect more data to see when and for which card they occur.

Gather analytics about card dismissals

---

app/src/main/java/be/ugent/zeus/hydra/common/network/Endpoints.java
app/src/main/java/be/ugent/zeus/hydra/news/UgentNewsRequest.java
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

With this change, we now no longer use student.ugent.be in the Android app 🎉 
Additionally, using the UGent URLs directly allows us to support English news if the app is set to English.

Migrate off old DSA API

---

.editorconfig
.github/workflows/ci.yml
.gitignore
app/build.gradle
app/secrets.properties.example

- Adds a GitHub Action that will automatically create a signed APK and GitHub release for certain tags.
- Removes Travis integration
In the long term, these automatic releases could be pushed to the Play Store automatically.
----
Security wise, the risk is not 0%: it is possible to get the keystore file from the actions. However, this requires write-access to the repo, which means it basically boils down to if we trust Zeus WPI members or not. (I assume we do). 
Note that other repositories with automatic deployment, such as https://github.com/ZeusWPI/hydra and https://github.com/ZeusWPI/zeus.ugent.be have the same problem.
However, one complication is that the Android keystore cannot be changed. In the case of the other repo's, we can always change SSH keys on the server.
For this …

Automatic releases

---

app/src/main/java/be/ugent/zeus/hydra/common/utils/DateUtils.java

Finally fixes #355. Apparently, the `TextStyle.FULL_STANDALONE` date formatter is buggy on Android.

Fix date names in tabs

---

app/src/open/java/be/ugent/zeus/hydra/common/barcode/OpenBarcodeScanner.java

This change was highly requested by all users of the open variant.
While the beep has its charms, it is better in most cases to not make
an unexpected sound. Additionally, the Play Store variant also doesn't
make a sound, so this makes the functionality equal.

Disable beep in open scanner

---

app/src/main/java/be/ugent/zeus/hydra/wpi/tap/cart/CartActivity.java
app/src/main/java/be/ugent/zeus/hydra/wpi/tap/product/ProductFragment.java
app/src/main/res/drawable/shortcut_tap_favourite.xml
app/src/main/res/drawable/shortcut_tap_favourite_foreground.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Allow pinning a shortcut to the homescreen, which opens the cart activity directly with the dagschotel preloaded. This should save at least two clicks when ordering dagschotels. It is basically a better version of a widget (since this is a shortcut, it needs no updates in the background).
This PR also shows all products by default, since the stock is not really kept up-to-date.

Dagschotel shortcut

---

app/src/main/java/be/ugent/zeus/hydra/wpi/tap/cart/CartActivity.java

The user can press the button to clear the cart before the cart has
loaded, in which case there is no cart to clear, so: null pointer.

Fix null pointer exception

---

app/src/main/java/be/ugent/zeus/hydra/MainActivity.java
app/src/main/java/be/ugent/zeus/hydra/common/utils/NetworkUtils.java
flake.lock
flake.nix

If there is no Play Store on the device, open the Ufora app in the browser instead. I couldn't find a generic "app store" intent, and even if it did exist, the Ufora app is only available from the Play Store.
Fix #628

Add fallback for missing Play Store

---

app/build.gradle

This is unfortunately used by the mjpeg library.
Fixes #627.

Include R8 rules for RxJava 1

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/res/xml/locales_config.xml

Only in API >= 33, since adding an in-app picker is a lot of work. Fixes #667

Support per-app language settings

---

app/src/main/java/be/ugent/zeus/hydra/urgent/MediaNotificationBuilder.java
flake.lock
flake.nix
gradle.properties

This is not the crash reported in Mattermost, but one I came across while looking at our analytics.

Fix bug in Urgent.fm

---

app/src/main/java/be/ugent/zeus/hydra/resto/RestoMenu.java

Fix a crash on older devices.
For those with access: https://console.firebase.google.com/project/hydra-142516/crashlytics/app/android:be.ugent.zeus.hydra/issues/183b608e3e634aceb237ea4bc002fc0f

Fix crash on older devices
