app/app.iml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/be/ugent/zeus/hydra/activities/Hydra.java
app/src/main/java/be/ugent/zeus/hydra/activities/SettingsActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/SettingsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Sorry, merge conflicts. Will resolve.

Settings are now properly commited.

---

app/src/main/java/be/ugent/zeus/hydra/fragments/SettingsFragment.java
app/src/main/java/be/ugent/zeus/hydra/notifications/NotificationScheduler.java
app/src/main/java/be/ugent/zeus/hydra/preference/Time.java
app/src/main/java/be/ugent/zeus/hydra/preference/TimePreference.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

The time of a notification is saved as an `int` now, and is accessed via a custom `Time` object which handles conversions between `int`, `String` and `Calendar`.

Better internal representation of time.

---

app/src/main/java/be/ugent/zeus/hydra/activities/resto/MenuActivity.java
app/src/main/java/be/ugent/zeus/hydra/fragments/resto/RestoFragment.java

I forgot this, should have been in pull request #71.

Use constant in activity as well

---

app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/SchamperViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/views/NowToolbar.java
app/src/main/res/layout/x_now_toolbar.xml

Fix some crashes on older versions, mainly issues with VectorDrawables

Fixes for older versions

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/be/ugent/zeus/hydra/activities/ActivityDetailActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/AssociationDetailActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/SchamperArticleActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/common/HydraActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/common/ToolbarActivity.java
app/src/main/java/be/ugent/zeus/hydra/models/association/Activity.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/adapters/ActivityListAdapter.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/SchamperViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/home/ActivityCardViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/home/SchamperViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/utils/html/Utils.java
app/src/main/res/drawable/ic_map_black_24dp.xml
app/src/main/res/drawable/ic_open_in_new_24dp.xml
app/src/main/res/drawable/ic_place_24dp.xml
app/src/main/res/drawable/ic_schedule_black_24dp.xml
app/src/main/res/layout/activity_announcement.xml
app/src/main/res/layout/activity_association_detail.xml
app/src/main/res/layout/activity_event_detail.xml
app/src/main/res/layout/activity_news_article.xml
app/src/main/res/layout/activity_schamper_article.xml
app/src/main/res/layout/home_card_schamper.xml
app/src/main/res/layout/x_separator_line.xml
app/src/main/res/menu/menu_event.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Re-design the event window to look more 'material'.
See old and new:

Re-design events

---

app/src/main/java/be/ugent/zeus/hydra/activities/ActivityDetailActivity.java

This time it should handle all possible errors with the image

Issue 48 part II

---

app/src/main/java/be/ugent/zeus/hydra/models/converters/AbstractDateJsonAdapter.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/adapters/ActivityListAdapter.java
app/src/main/java/be/ugent/zeus/hydra/utils/DateUtils.java

We hardcode all locales to Dutch for now, as the rest of the app is Dutch-only as well. (issue #83 )

Fix for issue #83

---

app/src/main/java/be/ugent/zeus/hydra/activities/minerva/CourseActivity.java
app/src/main/java/be/ugent/zeus/hydra/minerva/announcement/AnnouncementNotificationBuilder.java

Some improvements:
* Strip html from notification body
* Clickable notifications

Improve Minerva notifications

---

app/src/main/java/be/ugent/zeus/hydra/models/minerva/Course.java
app/src/main/java/be/ugent/zeus/hydra/requests/minerva/AgendaRequest.java

Use epoch seconds instead of milli seconds

Fix Minerva agenda

---

app/src/main/java/be/ugent/zeus/hydra/requests/minerva/MinervaRequest.java

Forgot commit

---

app/src/main/java/be/ugent/zeus/hydra/fragments/urgent/UrgentTrack.java
app/src/main/java/be/ugent/zeus/hydra/requests/UrgentUrlRequest.java
app/src/main/java/be/ugent/zeus/hydra/urgent/MusicService.java
app/src/main/java/be/ugent/zeus/hydra/urgent/track/Track.java
app/src/main/java/be/ugent/zeus/hydra/utils/StringUtils.java

Hardcoded IP-adressen moeten weg blijkbaar

---

app/src/main/java/be/ugent/zeus/hydra/activities/EventDetailActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/ExceptionDialogActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/OnboardingActivity.java
app/src/main/java/be/ugent/zeus/hydra/activities/sko/OverviewActivity.java
app/src/main/java/be/ugent/zeus/hydra/fragments/minerva/CourseInfoFragment.java
app/src/main/java/be/ugent/zeus/hydra/fragments/minerva/MinervaFragment.java
app/src/main/java/be/ugent/zeus/hydra/fragments/preferences/AboutFragment.java
app/src/main/java/be/ugent/zeus/hydra/fragments/urgent/UrgentFragment.java
app/src/main/java/be/ugent/zeus/hydra/homefeed/HomeFeedFragment.java
app/src/main/java/be/ugent/zeus/hydra/homefeed/content/minerva/agenda/MinervaAgendaViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/homefeed/content/minerva/announcement/MinervaAnnouncementViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/homefeed/content/minerva/login/MinervaLoginViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/homefeed/loader/HomeFeedLoader.java
app/src/main/java/be/ugent/zeus/hydra/minerva/announcement/AnnouncementNotificationBuilder.java
app/src/main/java/be/ugent/zeus/hydra/minerva/sync/SyncErrorNotification.java
app/src/main/java/be/ugent/zeus/hydra/notifications/NotificationCreator.java
app/src/main/java/be/ugent/zeus/hydra/plugins/OfflinePlugin.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/NewsItemViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/minerva/AgendaViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/minerva/AnnouncementViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/sko/ExhibitorViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/recyclerview/viewholder/sko/LineupViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/views/MenuTable.java
app/src/main/res/values/strings.xml

Do the first item and convert a lot of hard coded strings.

Work on #72

---

app/src/main/java/be/ugent/zeus/hydra/fragments/urgent/UrgentTrack.java

Urgent changed their config file.

Fix urgent.fm

---

app/src/main/java/be/ugent/zeus/hydra/data/database/minerva/CourseDao.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/MinervaCourseAdapter.java

Fix Minerva ordering resetting on sync

---

app/src/main/java/be/ugent/zeus/hydra/data/sync/announcement/Adapter.java
app/src/main/java/be/ugent/zeus/hydra/data/sync/announcement/AnnouncementNotificationBuilder.java
app/src/main/java/be/ugent/zeus/hydra/data/sync/course/Adapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/MinervaFragment.java

- Actually show notifications for announcements that are not emailed
- Remove notifications if they are present when logging out

Fix Minerva notifications

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/ui/sko/ArtistActivity.java
app/src/main/res/drawable/ic_library_music.xml
app/src/main/res/drawable/ic_search.xml
app/src/main/res/layout/activity_sko_artist.xml
app/src/main/res/menu/menu_sko.xml
app/src/main/res/values/strings.xml

Add a small feature on the SKO artist page: you can now search for the artist online, or search for the artist in your music collection (including any music app, as well as YouTube, ...)

Small SKO feature

---

app/src/main/java/be/ugent/zeus/hydra/data/models/library/Library.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/adapters/SearchableDiffAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/library/LibraryListAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/library/LibraryListFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/library/LibraryLiveData.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/library/LibraryViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/library/LibraryViewModel.java
app/src/main/res/layout/item_library.xml
app/src/main/res/menu/menu_library_list.xml
app/src/test/java/be/ugent/zeus/hydra/data/models/library/LibraryTest.java

This PR enables searching in the list of libraries.
Searching currently happens on the name and campus. For example, searching `boeken` will show all libraries with `boeken` in the name and all libraries where the campus has `boeken` in the name.

Search in library list

---

app/build.gradle
app/licenses.yml
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/adapters/GenericSearchableAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/adapters/SearchableDiffAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/viewholders/DateHeaderViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/DateHeaderViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventItem.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventLiveData.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/events/EventViewModel.java
app/src/main/java/be/ugent/zeus/hydra/utils/DateUtils.java
app/src/main/res/layout/fragment_activities.xml
app/src/main/res/layout/item_activity.xml
app/src/main/res/layout/item_events_date_header.xml
app/src/main/res/values/dimens.xml
app/src/test/java/be/ugent/zeus/hydra/utils/DateUtilsTest.java

A better UI for the list of events.
Before:
After:

Improved events UI

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/ui/common/recyclerview/adapters/MultiSelectSearchableAdapter.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/MainActivity.java
app/src/main/java/be/ugent/zeus/hydra/ui/preferences/MinervaFragment.java

Fix a bunch of crashes reported by Firebase.

Fix various bugs

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/HydraApplication.java
app/src/main/java/be/ugent/zeus/hydra/data/models/resto/Resto.java
app/src/main/java/be/ugent/zeus/hydra/data/network/requests/resto/MenuRequest.java
app/src/main/java/be/ugent/zeus/hydra/data/network/requests/resto/SelectableMetaRequest.java
app/src/main/java/be/ugent/zeus/hydra/ui/common/widgets/MenuTable.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/FeedLiveData.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/content/resto/RestoCardViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/content/resto/RestoMenuCard.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/homefeed/content/resto/RestoRequest.java
app/src/main/java/be/ugent/zeus/hydra/ui/main/resto/RestoLiveData.java
app/src/main/java/be/ugent/zeus/hydra/ui/preferences/RestoPreferenceFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/resto/SelectableMetaViewModel.java
app/src/main/java/be/ugent/zeus/hydra/ui/resto/menu/MenuActivity.java
app/src/main/java/be/ugent/zeus/hydra/ui/resto/menu/MenuFragment.java
app/src/main/java/be/ugent/zeus/hydra/ui/resto/menu/MenuLiveData.java
app/src/main/java/be/ugent/zeus/hydra/ui/resto/menu/MenuViewModel.java
app/src/main/res/layout/activity_resto.xml
app/src/main/res/layout/fragment_menu.xml
app/src/main/res/layout/x_simple_spinner_dropdown_item.xml
app/src/main/res/values/array.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_resto.xml
app/src/test/java/be/ugent/zeus/hydra/data/network/requests/resto/MenuRequestTest.java

Add the ability to choose a resto from any of the ones on the meta list.

Resto chooser

---

app/src/main/java/be/ugent/zeus/hydra/ui/EventDetailActivity.java
app/src/main/res/menu/menu_event.xml

This allows the user to basically copy association events to their phone's calendar.

Allow adding association events to calendar

---

app/src/main/java/be/ugent/zeus/hydra/data/network/requests/minerva/MinervaRequest.java

This pull request is resubmitted because of a problem with Travis.

Fix StackOverflowException again

---

app/src/main/java/be/ugent/zeus/hydra/ui/main/UrgentFragment.java
app/src/main/res/drawable/ic_facebook.xml
app/src/main/res/drawable/ic_instagram.xml
app/src/main/res/drawable/ic_youtube.xml
app/src/main/res/layout/fragment_urgent.xml

added links to the urgentfm page of facebook, youtube, instagram and the urgent website itself

added social links

---

app/src/main/java/be/ugent/zeus/hydra/common/database/Database.java
app/src/main/java/be/ugent/zeus/hydra/feed/HomeFeedFragment.java

Some small fixes and improvements

Small fixes

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/association/event/Event.java
app/src/main/java/be/ugent/zeus/hydra/association/event/EventDetailActivity.java
app/src/main/java/be/ugent/zeus/hydra/common/converter/DateTypeConverters.java
app/src/main/res/values/strings.xml

Hotfix for crash en "brakke api"

Fix for null end date

---

app/src/main/java/be/ugent/zeus/hydra/common/network/InstanceProvider.java
app/src/main/java/be/ugent/zeus/hydra/common/network/InterceptingWebViewClient.java
app/src/main/java/be/ugent/zeus/hydra/common/ui/WebViewActivity.java
app/src/main/java/be/ugent/zeus/hydra/sko/MapFragment.java
app/src/main/res/layout/drawer_header.xml

- Fix compat issues on Android API <= 20, see https://github.com/ZeusWPI/ansible-config/commit/548bc6e0c92cda761e705d2183dca24c819af252.
- Fix image colour crash on older devices

Security++++

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/association/event/list/EventListConverter.java
app/src/main/java/be/ugent/zeus/hydra/association/news/NewsArticleActivity.java
app/src/main/java/be/ugent/zeus/hydra/common/article/CustomTabPreferenceFragment.java
app/src/main/java/be/ugent/zeus/hydra/common/preferences/SettingsActivity.java
app/src/main/java/be/ugent/zeus/hydra/common/ui/recyclerview/adapters/MultiSelectSearchableAdapter.java
app/src/main/java/be/ugent/zeus/hydra/minerva/auth/AuthActivity.java
app/src/main/java/be/ugent/zeus/hydra/schamper/FullArticleActivity.java
app/src/main/res/xml/pref_headers.xml
app/src/test/java/be/ugent/zeus/hydra/association/news/NewsArticleActivityTest.java
app/src/test/java/be/ugent/zeus/hydra/feed/cards/implementations/news/NewsItemViewHolderTest.java
app/src/test/java/be/ugent/zeus/hydra/feed/cards/implementations/schamper/SchamperViewHolderTest.java

- Update dependencies
- Fix two `NullPointerException`s reported through Crashlytics
- Minor cleanup

Small cleanup and bugfixes

---

app/build.gradle
build.gradle

Fix crash on startup in onboarding

---

app/src/main/java/be/ugent/zeus/hydra/common/network/InstanceProvider.java
app/src/main/java/be/ugent/zeus/hydra/urgent/ProgrammeInformation.java
app/src/main/java/be/ugent/zeus/hydra/urgent/UrgentFragment.java
app/src/main/java/be/ugent/zeus/hydra/urgent/UrgentInfo.java
app/src/main/java/be/ugent/zeus/hydra/urgent/player/UrgentTrackProvider.java
app/src/main/res/layout/fragment_urgent.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/resources/urgent.json

Since implementing ZeusWPI/hydra#297, we can now display the image and
description of the programme.

Add Urgent.fm programme meta data

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/association/event/list/EventFragment.java
app/src/main/java/be/ugent/zeus/hydra/association/news/list/NewsFragment.java
app/src/main/java/be/ugent/zeus/hydra/feed/HomeFeedFragment.java
app/src/main/java/be/ugent/zeus/hydra/info/InfoFragment.java
app/src/main/java/be/ugent/zeus/hydra/info/InfoType.java
app/src/main/java/be/ugent/zeus/hydra/library/list/LibraryListFragment.java
app/src/main/java/be/ugent/zeus/hydra/resto/SingleDayFragment.java
app/src/main/java/be/ugent/zeus/hydra/resto/extrafood/FoodFragment.java
app/src/main/java/be/ugent/zeus/hydra/resto/menu/RestoFragment.java
app/src/main/java/be/ugent/zeus/hydra/schamper/list/SchamperFragment.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/LineupFragment.java
app/src/main/res/drawable/info_ufora.xml
build.gradle

- Add icon for Ufora
- Update libraries

Various updates

---

.travis.yml
app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/common/ui/customtabs/CustomTabsHelper.java
app/src/main/java/be/ugent/zeus/hydra/common/ui/customtabs/HasTabActivityHelper.java
app/src/main/java/be/ugent/zeus/hydra/onboarding/ReportingFragment.java
app/src/main/java/be/ugent/zeus/hydra/sko/OverviewActivity.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/Artist.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/ArtistDetailsActivity.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/ArtistOrTitle.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/ArtistViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/LineupFragment.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/LineupRequest.java
app/src/main/java/be/ugent/zeus/hydra/sko/lineup/LineupViewModel.java
app/src/main/res/drawable/gradient_black_bottom.xml
app/src/main/res/drawable/gradient_black_bottom_top.xml
app/src/main/res/layout-sw600dp-land/activity_library_details.xml
app/src/main/res/layout-sw900dp/activity_library_details.xml
app/src/main/res/layout/activity_library_details.xml
app/src/main/res/layout/activity_schamper_article.xml
app/src/main/res/layout/activity_sko_artist.xml
app/src/main/res/layout/fragment_onboarding_reporting.xml
app/src/main/res/layout/item_sko_lineup_artist.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/formatters.xml
app/src/main/res/values/strings.xml
app/src/test/java/be/ugent/zeus/hydra/TestApp.java
app/src/test/java/be/ugent/zeus/hydra/sko/lineup/ArtistTest.java
app/src/test/java/be/ugent/zeus/hydra/testing/Utils.java
app/src/test/resources/sko_lineup.json

- Some API fields have changed
- Fix some wonky scroll effects
Unrelated:
- Add button to read privacy policy in onboarding

Update SKO line-up

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/MainActivity.java

- Update dependencies
- By using our fork of one library, prevent a crash
- Don't use debug string in the code

Updates & fixes

---

app/src/test/java/be/ugent/zeus/hydra/MainActivityTest.java
app/src/test/java/be/ugent/zeus/hydra/association/event/EventDetailsActivityDeviceTest.java
app/src/test/java/be/ugent/zeus/hydra/association/event/EventDetailsActivityTest.java

Maybe we can re-enable it one day, but not today.

Ignore unreliable test

---

app/src/main/java/be/ugent/zeus/hydra/feed/preferences/HomeFragment.java

Fix crash in home feed preferences

---

build.gradle

Reverts ZeusWPI/hydra-android#468

Revert "Bump gradle from 4.2.2 to 7.0.0"

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
README.md
app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/common/utils/ColourUtils.java
app/src/test/java/be/ugent/zeus/hydra/association/event/EventTest.java
buildSrc/build.gradle
flake.lock
flake.nix
gradle/wrapper/gradle-wrapper.properties

- Bump gradle
- Add nix flake
- Remove obsolete test
- Bump library

Some chores

---

app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

Fix unintended change

---

app/build.gradle

Back to the stable version at last.

Bump material components

---

app/src/main/java/be/ugent/zeus/hydra/resto/SingleDayFragment.java
app/src/main/java/be/ugent/zeus/hydra/resto/menu/RestoFragment.java
app/src/main/res/layout/fragment_menu.xml
app/src/main/res/menu/menu_resto.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

Move order online button to overflow menu

---

app/src/main/java/be/ugent/zeus/hydra/wpi/tap/cart/CartActivity.java
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

This is really unprofessional...

Translate untranslated string

---

app/build.gradle
app/src/main/java/be/ugent/zeus/hydra/info/InfoViewHolder.java
flake.nix
material-intro/build.gradle

There are no pressing issues I think. Afterwards, we can support per-app language preferences. Back button

Target Android 33

---

app/src/main/java/be/ugent/zeus/hydra/wpi/tap/cart/CartActivity.java
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

Add share menu for missing barcode

---

app/src/main/java/be/ugent/zeus/hydra/wpi/tab/create/FormActivity.java
app/src/main/java/be/ugent/zeus/hydra/wpi/tab/create/Member.java
app/src/main/java/be/ugent/zeus/hydra/wpi/tab/create/MemberRequest.java
app/src/main/java/be/ugent/zeus/hydra/wpi/tab/create/TransactionViewModel.java
app/src/main/res/layout/activity_wpi_tab_transaction_form.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

Autocomplete member names when creating tab transaction

---

app/src/main/java/be/ugent/zeus/hydra/common/ui/widgets/MenuTable.java
app/src/main/java/be/ugent/zeus/hydra/feed/cards/resto/RestoCardViewHolder.java
app/src/main/java/be/ugent/zeus/hydra/feed/cards/resto/RestoKindCommand.java
app/src/main/java/be/ugent/zeus/hydra/feed/cards/resto/RestoMenuCard.java
app/src/main/java/be/ugent/zeus/hydra/feed/cards/resto/RestoRequest.java
app/src/main/java/be/ugent/zeus/hydra/feed/preferences/HomeFragment.java
app/src/main/res/values-en/strings.xml
app/src/main/res/values/array.xml
app/src/main/res/values/strings.xml
app/src/open/res/xml/pref_home_feed.xml
app/src/store/res/xml/pref_home_feed.xml

While this PR might not be very useful at the moment since cold meals don't seem to be in the menu any more, it can't hurt for the future.

Rework meal display preferences in home feed

---

buildSrc/src/main/groovy/be/ugent/zeus/hydra/licenses/LicenseMap.groovy

Add missing licenses to Gradle plugin

---

app/build.gradle
build.gradle
gradle.properties

Gradle 8 has issues with the snapshots. This should hopefully fix the CI.

Use our own fork of Easy Random for now

---

app/src/main/java/be/ugent/zeus/hydra/common/ui/widgets/DisplayableMenu.java

See https://console.firebase.google.com/project/hydra-142516/crashlytics/app/android:be.ugent.zeus.hydra/issues/e1eacf5bb9626d5821c9acb5ff97b011 for those with access.

Fix NullPointerException in resto menu

---

app/src/main/java/be/ugent/zeus/hydra/wpi/tap/cart/Cart.java

Fix bug with cart

---

.github/workflows/ci.yml
android-versions.toml
app/build.gradle.kts
flake.lock
flake.nix
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

I don't think any of the changes affect us.

Bump to API level 35
